package main

import (
	"io"
	"strings"
	"text/template"
	"unicode"
)

type templateData struct {
	Pkg            string
	TypeName       string
	ExportedType   string
	AllSliceFunc   string
	AllFunc        string
	NumberType     string
	NamesMapVar    string
	ValidMapVar    string
	StringMapVar   string
	ParseFunc      string
	StringToFunc   string
	NumberToFunc   string
	ExhaustiveFunc string
	UnderlyingType string
	InvalidConst   string
	Values         []valueData
	ValidValues    []valueData
}

type valueData struct {
	UnexportedConst string
	ExportedConst   string
	StringName      string
	IsInvalid       bool
	IotaIndex       int
}

func generate(w io.Writer, enums []enumType) error {
	if len(enums) == 0 {
		return nil
	}
	if err := fileHeaderTemplate.Execute(w, enums[0].pkg); err != nil {
		return err
	}
	for _, e := range enums {
		if err := generateEnum(w, e); err != nil {
			return err
		}
	}
	return nil
}

func generateEnum(w io.Writer, e enumType) error {
	exported := exportName(e.typeName)
	lower := e.typeName

	var values []valueData
	for _, v := range e.values {
		values = append(values, valueData{
			UnexportedConst: v.unexportedConst,
			ExportedConst:   exportName(v.unexportedConst),
			StringName:      v.stringName,
			IsInvalid:       v.isInvalid,
			IotaIndex:       v.iotaIndex,
		})
	}

	var validValues []valueData
	for _, v := range values {
		if !v.IsInvalid {
			validValues = append(validValues, v)
		}
	}

	invalidConst := exported
	if len(values) > 0 {
		invalidConst = values[0].ExportedConst
	}

	d := templateData{
		Pkg:            e.pkg,
		TypeName:       e.typeName,
		ExportedType:   exported,
		AllSliceFunc:   "all" + pluralize(exported),
		AllFunc:        "All" + pluralize(exported),
		NumberType:     lower + "Number",
		NamesMapVar:    lower + "NamesMap",
		ValidMapVar:    "valid" + pluralize(exported),
		StringMapVar:   pluralize(lower) + "NameMap",
		ParseFunc:      "Parse" + exported,
		StringToFunc:   "stringTo" + exported,
		NumberToFunc:   "numberTo" + exported,
		ExhaustiveFunc: "Exhaustive" + pluralize(exported),
		UnderlyingType: e.underlyingType,
		InvalidConst:   invalidConst,
		Values:         values,
		ValidValues:    validValues,
	}

	return enumBodyTemplate.Execute(w, d)
}

func exportName(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func pluralize(s string) string {
	if s == "" {
		return ""
	}
	lower := strings.ToLower(s)
	switch {
	case strings.HasSuffix(lower, "ch") || strings.HasSuffix(lower, "sh") ||
		strings.HasSuffix(lower, "x") || strings.HasSuffix(lower, "z") ||
		strings.HasSuffix(lower, "s"):
		return s + "es"
	case strings.HasSuffix(lower, "y") && len(s) >= 2 && !isVowel(rune(lower[len(lower)-2])):
		return s[:len(s)-1] + "ies"
	default:
		return s + "s"
	}
}

func isVowel(r rune) bool {
	return r == 'a' || r == 'e' || r == 'i' || r == 'o' || r == 'u'
}

var fileHeaderTemplate = template.Must(template.New("header").Parse(
	`// Code generated by go-enum. DO NOT EDIT.

package {{.}}

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"math"
)
`))

var enumBodyTemplate = template.Must(template.New("enum").Funcs(template.FuncMap{
	"bq": func() string { return "`" },
}).Parse(`
// {{.ExportedType}} is the exported enum type.
type {{.ExportedType}} {{.UnderlyingType}}

const (
{{- range $i, $v := .Values}}
	{{$v.ExportedConst}}{{if eq $i 0}} {{$.ExportedType}} = iota{{end}}
{{- end}}
)

func {{.AllSliceFunc}}() []{{.ExportedType}} {
	return []{{.ExportedType}}{
{{- range .ValidValues}}
		{{.ExportedConst}},
{{- end}}
	}
}

// {{.AllFunc}} returns an iterator over all valid {{.ExportedType}} values.
func {{.AllFunc}}() iter.Seq[{{.ExportedType}}] {
	return func(yield func({{.ExportedType}}) bool) {
		for _, v := range {{.AllSliceFunc}}() {
			if !yield(v) {
				return
			}
		}
	}
}

var {{.NamesMapVar}} = map[{{.ExportedType}}]string{
{{- range .Values}}
	{{.ExportedConst}}: "{{.StringName}}",
{{- end}}
}

// String implements fmt.Stringer.
func (v {{.ExportedType}}) String() string {
	if s, ok := {{.NamesMapVar}}[v]; ok {
		return s
	}
	return fmt.Sprintf("{{.ExportedType}}(%d)", {{.UnderlyingType}}(v))
}

var {{.ValidMapVar}} = map[{{.ExportedType}}]bool{
{{- range .Values}}
	{{.ExportedConst}}: {{if .IsInvalid}}false{{else}}true{{end}},
{{- end}}
}

// IsValid reports whether v is a valid {{.ExportedType}} value.
func (v {{.ExportedType}}) IsValid() bool {
	return {{.ValidMapVar}}[v]
}

var {{.StringMapVar}} = map[string]{{.ExportedType}}{
{{- range .Values}}
	"{{.StringName}}": {{.ExportedConst}},
{{- end}}
}

func {{.StringToFunc}}(s string) *{{.ExportedType}} {
	if v, ok := {{.StringMapVar}}[s]; ok {
		return &v
	}
	return nil
}

type {{.NumberType}} interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 |
		~float32 | ~float64
}

func {{.NumberToFunc}}[T {{.NumberType}}](num T) *{{.ExportedType}} {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	v := {{.ExportedType}}(int(f))
	if !v.IsValid() {
		return nil
	}
	return &v
}

// {{.ParseFunc}} parses any supported input into a {{.ExportedType}} value.
func {{.ParseFunc}}(input any) ({{.ExportedType}}, error) {
	switch v := input.(type) {
	case {{.ExportedType}}:
		return v, nil
	case string:
		if r := {{.StringToFunc}}(v); r != nil {
			return *r, nil
		}
	case fmt.Stringer:
		if r := {{.StringToFunc}}(v.String()); r != nil {
			return *r, nil
		}
	case []byte:
		if r := {{.StringToFunc}}(string(v)); r != nil {
			return *r, nil
		}
	case int:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case int8:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case int16:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case int32:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case int64:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case uint:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case uint8:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case uint16:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case uint32:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case uint64:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case float32:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	case float64:
		if r := {{.NumberToFunc}}(v); r != nil {
			return *r, nil
		}
	default:
		return {{.InvalidConst}}, fmt.Errorf("{{.ParseFunc}}: unsupported type %T", input)
	}
	return {{.InvalidConst}}, fmt.Errorf("{{.ParseFunc}}: invalid value %v", input)
}

// {{.ExhaustiveFunc}} calls f for every valid {{.ExportedType}} value.
func {{.ExhaustiveFunc}}(f func({{.ExportedType}})) {
	for _, v := range {{.AllSliceFunc}}() {
		f(v)
	}
}

// MarshalJSON implements json.Marshaler.
func (v {{.ExportedType}}) MarshalJSON() ([]byte, error) {
	return []byte({{bq}}"{{bq}} + v.String() + {{bq}}"{{bq}}), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *{{.ExportedType}}) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(b, {{bq}}"{{bq}})
	r, err := {{.ParseFunc}}(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v {{.ExportedType}}) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *{{.ExportedType}}) UnmarshalText(b []byte) error {
	r, err := {{.ParseFunc}}(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (v {{.ExportedType}}) MarshalBinary() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (v *{{.ExportedType}}) UnmarshalBinary(b []byte) error {
	r, err := {{.ParseFunc}}(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalYAML implements yaml.Marshaler.
func (v {{.ExportedType}}) MarshalYAML() (interface{}, error) {
	return v.String(), nil
}

// UnmarshalYAML implements yaml.Unmarshaler (v3 signature).
func (v *{{.ExportedType}}) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}
	r, err := {{.ParseFunc}}(s)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Scan implements database/sql.Scanner.
func (v *{{.ExportedType}}) Scan(src any) error {
	r, err := {{.ParseFunc}}(src)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Value implements database/sql/driver.Valuer.
func (v {{.ExportedType}}) Value() (driver.Value, error) {
	return v.String(), nil
}

// Compile-time check: errors here mean the source enum changed; re-run go-enum.
func _() {
	var x [{{len .Values}}]struct{}
{{- range .Values}}
{{- if eq .IotaIndex 0}}
	_ = x[{{.UnexportedConst}}]
{{- else}}
	_ = x[{{.UnexportedConst}}-{{.IotaIndex}}]
{{- end}}
{{- end}}
}
`))
