// Code generated by go-enum. DO NOT EDIT.

package examples

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"math"
)

// OrderStatus is the exported enum type.
type OrderStatus int

const (
	OrderStatusUnknown OrderStatus = iota
	OrderStatusPending
	OrderStatusConfirmed
	OrderStatusProcessing
	OrderStatusShipped
	OrderStatusDelivered
	OrderStatusCancelled
	OrderStatusRefunded
)

func allOrderStatuses() []OrderStatus {
	return []OrderStatus{
		OrderStatusPending,
		OrderStatusConfirmed,
		OrderStatusProcessing,
		OrderStatusShipped,
		OrderStatusDelivered,
		OrderStatusCancelled,
		OrderStatusRefunded,
	}
}

// AllOrderStatuses returns an iterator over all valid OrderStatus values.
func AllOrderStatuses() iter.Seq[OrderStatus] {
	return func(yield func(OrderStatus) bool) {
		for _, v := range allOrderStatuses() {
			if !yield(v) {
				return
			}
		}
	}
}

var orderStatusNamesMap = map[OrderStatus]string{
	OrderStatusUnknown:    "unknown",
	OrderStatusPending:    "pending",
	OrderStatusConfirmed:  "confirmed",
	OrderStatusProcessing: "processing",
	OrderStatusShipped:    "shipped",
	OrderStatusDelivered:  "delivered",
	OrderStatusCancelled:  "cancelled",
	OrderStatusRefunded:   "refunded",
}

// String implements fmt.Stringer.
func (v OrderStatus) String() string {
	if s, ok := orderStatusNamesMap[v]; ok {
		return s
	}
	return fmt.Sprintf("OrderStatus(%d)", int(v))
}

var validOrderStatuses = map[OrderStatus]bool{
	OrderStatusUnknown:    false,
	OrderStatusPending:    true,
	OrderStatusConfirmed:  true,
	OrderStatusProcessing: true,
	OrderStatusShipped:    true,
	OrderStatusDelivered:  true,
	OrderStatusCancelled:  true,
	OrderStatusRefunded:   true,
}

// IsValid reports whether v is a valid OrderStatus value.
func (v OrderStatus) IsValid() bool {
	return validOrderStatuses[v]
}

var orderStatusesNameMap = map[string]OrderStatus{
	"unknown":    OrderStatusUnknown,
	"pending":    OrderStatusPending,
	"confirmed":  OrderStatusConfirmed,
	"processing": OrderStatusProcessing,
	"shipped":    OrderStatusShipped,
	"delivered":  OrderStatusDelivered,
	"cancelled":  OrderStatusCancelled,
	"refunded":   OrderStatusRefunded,
}

func stringToOrderStatus(s string) *OrderStatus {
	if v, ok := orderStatusesNameMap[s]; ok {
		return &v
	}
	return nil
}

type orderStatusNumber interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 |
		~float32 | ~float64
}

func numberToOrderStatus[T orderStatusNumber](num T) *OrderStatus {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	v := OrderStatus(int(f))
	if !v.IsValid() {
		return nil
	}
	return &v
}

// ParseOrderStatus parses any supported input into a OrderStatus value.
func ParseOrderStatus(input any) (OrderStatus, error) {
	switch v := input.(type) {
	case OrderStatus:
		return v, nil
	case string:
		if r := stringToOrderStatus(v); r != nil {
			return *r, nil
		}
	case fmt.Stringer:
		if r := stringToOrderStatus(v.String()); r != nil {
			return *r, nil
		}
	case []byte:
		if r := stringToOrderStatus(string(v)); r != nil {
			return *r, nil
		}
	case int:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case int8:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case int16:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case int32:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case int64:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case uint:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case uint8:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case uint16:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case uint32:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case uint64:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case float32:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	case float64:
		if r := numberToOrderStatus(v); r != nil {
			return *r, nil
		}
	default:
		return OrderStatusUnknown, fmt.Errorf("ParseOrderStatus: unsupported type %T", input)
	}
	return OrderStatusUnknown, fmt.Errorf("ParseOrderStatus: invalid value %v", input)
}

// ExhaustiveOrderStatuses calls f for every valid OrderStatus value.
func ExhaustiveOrderStatuses(f func(OrderStatus)) {
	for _, v := range allOrderStatuses() {
		f(v)
	}
}

// MarshalJSON implements json.Marshaler.
func (v OrderStatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + v.String() + `"`), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *OrderStatus) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(b, `"`)
	r, err := ParseOrderStatus(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v OrderStatus) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *OrderStatus) UnmarshalText(b []byte) error {
	r, err := ParseOrderStatus(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (v OrderStatus) MarshalBinary() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (v *OrderStatus) UnmarshalBinary(b []byte) error {
	r, err := ParseOrderStatus(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalYAML implements yaml.Marshaler.
func (v OrderStatus) MarshalYAML() (interface{}, error) {
	return v.String(), nil
}

// UnmarshalYAML implements yaml.Unmarshaler (v3 signature).
func (v *OrderStatus) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}
	r, err := ParseOrderStatus(s)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Scan implements database/sql.Scanner.
func (v *OrderStatus) Scan(src any) error {
	r, err := ParseOrderStatus(src)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Value implements database/sql/driver.Valuer.
func (v OrderStatus) Value() (driver.Value, error) {
	return v.String(), nil
}

// Compile-time check: errors here mean the source enum changed; re-run go-enum.
func _() {
	var x [8]struct{}
	_ = x[orderStatusUnknown]
	_ = x[orderStatusPending-1]
	_ = x[orderStatusConfirmed-2]
	_ = x[orderStatusProcessing-3]
	_ = x[orderStatusShipped-4]
	_ = x[orderStatusDelivered-5]
	_ = x[orderStatusCancelled-6]
	_ = x[orderStatusRefunded-7]
}

// PaymentMethod is the exported enum type.
type PaymentMethod int

const (
	PaymentMethodUnknown PaymentMethod = iota
	PaymentMethodCard
	PaymentMethodBankTransfer
	PaymentMethodWallet
	PaymentMethodCrypto
)

func allPaymentMethods() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodCard,
		PaymentMethodBankTransfer,
		PaymentMethodWallet,
		PaymentMethodCrypto,
	}
}

// AllPaymentMethods returns an iterator over all valid PaymentMethod values.
func AllPaymentMethods() iter.Seq[PaymentMethod] {
	return func(yield func(PaymentMethod) bool) {
		for _, v := range allPaymentMethods() {
			if !yield(v) {
				return
			}
		}
	}
}

var paymentMethodNamesMap = map[PaymentMethod]string{
	PaymentMethodUnknown:      "unknown",
	PaymentMethodCard:         "card",
	PaymentMethodBankTransfer: "bank transfer",
	PaymentMethodWallet:       "wallet",
	PaymentMethodCrypto:       "crypto",
}

// String implements fmt.Stringer.
func (v PaymentMethod) String() string {
	if s, ok := paymentMethodNamesMap[v]; ok {
		return s
	}
	return fmt.Sprintf("PaymentMethod(%d)", int(v))
}

var validPaymentMethods = map[PaymentMethod]bool{
	PaymentMethodUnknown:      false,
	PaymentMethodCard:         true,
	PaymentMethodBankTransfer: true,
	PaymentMethodWallet:       true,
	PaymentMethodCrypto:       true,
}

// IsValid reports whether v is a valid PaymentMethod value.
func (v PaymentMethod) IsValid() bool {
	return validPaymentMethods[v]
}

var paymentMethodsNameMap = map[string]PaymentMethod{
	"unknown":       PaymentMethodUnknown,
	"card":          PaymentMethodCard,
	"bank transfer": PaymentMethodBankTransfer,
	"wallet":        PaymentMethodWallet,
	"crypto":        PaymentMethodCrypto,
}

func stringToPaymentMethod(s string) *PaymentMethod {
	if v, ok := paymentMethodsNameMap[s]; ok {
		return &v
	}
	return nil
}

type paymentMethodNumber interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64 |
		~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 |
		~float32 | ~float64
}

func numberToPaymentMethod[T paymentMethodNumber](num T) *PaymentMethod {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	v := PaymentMethod(int(f))
	if !v.IsValid() {
		return nil
	}
	return &v
}

// ParsePaymentMethod parses any supported input into a PaymentMethod value.
func ParsePaymentMethod(input any) (PaymentMethod, error) {
	switch v := input.(type) {
	case PaymentMethod:
		return v, nil
	case string:
		if r := stringToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case fmt.Stringer:
		if r := stringToPaymentMethod(v.String()); r != nil {
			return *r, nil
		}
	case []byte:
		if r := stringToPaymentMethod(string(v)); r != nil {
			return *r, nil
		}
	case int:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case int8:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case int16:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case int32:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case int64:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case uint:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case uint8:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case uint16:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case uint32:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case uint64:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case float32:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	case float64:
		if r := numberToPaymentMethod(v); r != nil {
			return *r, nil
		}
	default:
		return PaymentMethodUnknown, fmt.Errorf("ParsePaymentMethod: unsupported type %T", input)
	}
	return PaymentMethodUnknown, fmt.Errorf("ParsePaymentMethod: invalid value %v", input)
}

// ExhaustivePaymentMethods calls f for every valid PaymentMethod value.
func ExhaustivePaymentMethods(f func(PaymentMethod)) {
	for _, v := range allPaymentMethods() {
		f(v)
	}
}

// MarshalJSON implements json.Marshaler.
func (v PaymentMethod) MarshalJSON() ([]byte, error) {
	return []byte(`"` + v.String() + `"`), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *PaymentMethod) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(b, `"`)
	r, err := ParsePaymentMethod(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalText implements encoding.TextMarshaler.
func (v PaymentMethod) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (v *PaymentMethod) UnmarshalText(b []byte) error {
	r, err := ParsePaymentMethod(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalBinary implements encoding.BinaryMarshaler.
func (v PaymentMethod) MarshalBinary() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (v *PaymentMethod) UnmarshalBinary(b []byte) error {
	r, err := ParsePaymentMethod(b)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// MarshalYAML implements yaml.Marshaler.
func (v PaymentMethod) MarshalYAML() (interface{}, error) {
	return v.String(), nil
}

// UnmarshalYAML implements yaml.Unmarshaler (v3 signature).
func (v *PaymentMethod) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}
	r, err := ParsePaymentMethod(s)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Scan implements database/sql.Scanner.
func (v *PaymentMethod) Scan(src any) error {
	r, err := ParsePaymentMethod(src)
	if err != nil {
		return err
	}
	*v = r
	return nil
}

// Value implements database/sql/driver.Valuer.
func (v PaymentMethod) Value() (driver.Value, error) {
	return v.String(), nil
}

// Compile-time check: errors here mean the source enum changed; re-run go-enum.
func _() {
	var x [5]struct{}
	_ = x[paymentMethodUnknown]
	_ = x[paymentMethodCard-1]
	_ = x[paymentMethodBankTransfer-2]
	_ = x[paymentMethodWallet-3]
	_ = x[paymentMethodCrypto-4]
}
